import { NextResponse, type NextRequest } from "next/server";

import { generatePreviewSlug, computeStaleAfter } from "@/lib/preview/slug";
import { buildNormalizedHospitalForLead } from "@/lib/normalize/integration";
import {
  createSupabaseServiceClient,
  isSupabaseConfigured,
} from "@/lib/supabase/server";

export const runtime = "nodejs";

function jsonError(message: string, status = 400) {
  return NextResponse.json({ ok: false, message }, { status });
}

const disclaimerEn =
  "UNOFFICIAL PREVIEW — This page was generated by Nasken AI as a technology preview. It is not affiliated with, endorsed by, or published by the hospital. All information shown was sourced from publicly available data. This page is not a medical recommendation.";

const disclaimerKn =
  "ಅನಧಿಕೃತ ಪೂರ್ವವೀಕ್ಷಣೆ — ಈ ಪುಟವನ್ನು ನ್ಯಾಸ್ಕನ್ AI ತಂತ್ರಜ್ಞಾನ ಪೂರ್ವವೀಕ್ಷಣೆಯಾಗಿ ರಚಿಸಿದೆ. ಇದು ಆಸ್ಪತ್ರೆಯಿಂದ ಅಧಿಕೃತವಾಗಿ ಪ್ರಕಟಿಸಲ್ಪಟ್ಟಿಲ್ಲ. ತೋರಿಸಲಾದ ಎಲ್ಲಾ ಮಾಹಿತಿಯನ್ನು ಸಾರ್ವಜನಿಕವಾಗಿ ಲಭ್ಯವಿರುವ ಡೇಟಾದಿಂದ ಪಡೆಯಲಾಗಿದೆ. ಇದು ವೈದ್ಯಕೀಯ ಶಿಫಾರಸು ಅಲ್ಲ.";

/**
 * POST /api/leads/[leadId]/deploy
 *
 * Creates (or reuses) a preview row for a lead. The preview renders through the
 * canonical crawl → normalize → eligibility → Hospital V1 path, so deployment
 * gates on a normalizable first-party model (not on legacy generated content).
 */
export async function POST(
  _request: NextRequest,
  context: { params: Promise<{ leadId: string }> },
) {
  if (!isSupabaseConfigured()) {
    return jsonError("Supabase is not configured.", 503);
  }

  const { leadId } = await context.params;
  const supabase = createSupabaseServiceClient();

  const { data: lead, error: leadError } = await supabase
    .from("leads")
    .select("id")
    .eq("id", leadId)
    .single();
  if (leadError || !lead) return jsonError("Lead not found.", 404);

  // Deploy gate: there must be a normalizable first-party model to render.
  const { model } = await buildNormalizedHospitalForLead(supabase, leadId);
  if (model.status === "FAILED") {
    return jsonError("No normalizable first-party content. Crawl the site first.", 422);
  }

  // Idempotent: reuse an existing live preview for this lead.
  const { data: existing } = await supabase
    .from("previews")
    .select("id,slug,status")
    .eq("lead_id", leadId)
    .neq("status", "REMOVED")
    .order("created_at", { ascending: false })
    .limit(1)
    .maybeSingle();
  if (existing) {
    return NextResponse.json({ ok: true, preview: existing, previewUrl: `/preview/${existing.slug}`, reused: true });
  }

  const slug = generatePreviewSlug();
  const { data: preview, error: previewError } = await supabase
    .from("previews")
    .insert({
      lead_id: leadId,
      slug,
      disclaimer_en: disclaimerEn,
      disclaimer_kn: disclaimerKn,
      noindex: true,
      status: "READY",
      deployed_at: new Date().toISOString(),
      stale_after: computeStaleAfter().toISOString(),
    })
    .select("id,slug,status")
    .single();
  if (previewError) {
    return jsonError(`Failed to create preview: ${previewError.message}`, 500);
  }

  await supabase.from("leads").update({ status: "PREVIEW_READY" }).eq("id", leadId);

  return NextResponse.json({ ok: true, preview, previewUrl: `/preview/${slug}`, status: model.status });
}
