import { NextResponse, type NextRequest } from "next/server";

import type { Json } from "@/lib/database/types";
import { generatePreviewSlug, computeStaleAfter } from "@/lib/preview/slug";
import { validateClaims } from "@/lib/content/claim-validator";
import { validateKannada } from "@/lib/content/kannada-validator";
import {
  evaluateDeployState,
  evaluateDeployValidation,
} from "@/lib/content/content-workflow";
import type { GeneratedContent } from "@/lib/content/content-schema";
import {
  createSupabaseServiceClient,
  isSupabaseConfigured,
} from "@/lib/supabase/server";

export const runtime = "nodejs";

function jsonError(message: string, status = 400) {
  return NextResponse.json({ ok: false, message }, { status });
}

const disclaimerEn =
  "UNOFFICIAL PREVIEW — This page was generated by Nasken AI as a technology preview. It is not affiliated with, endorsed by, or published by the hospital. All information shown was sourced from publicly available data and verified by a human reviewer. This page is not a medical recommendation.";

const disclaimerKn =
  "ಅನಧಿಕೃತ ಪೂರ್ವವೀಕ್ಷಣೆ — ಈ ಪುಟವನ್ನು ನ್ಯಾಸ್ಕನ್ AI ತಂತ್ರಜ್ಞಾನ ಪೂರ್ವವೀಕ್ಷಣೆಯಾಗಿ ರಚಿಸಿದೆ. ಇದು ಆಸ್ಪತ್ರೆಯಿಂದ ಅಧಿಕೃತವಾಗಿ ಪ್ರಕಟಿಸಲ್ಪಟ್ಟಿಲ್ಲ. ತೋರಿಸಲಾದ ಎಲ್ಲಾ ಮಾಹಿತಿಯನ್ನು ಸಾರ್ವಜನಿಕವಾಗಿ ಲಭ್ಯವಿರುವ ಡೇಟಾದಿಂದ ಪಡೆಯಲಾಗಿದೆ. ಇದು ವೈದ್ಯಕೀಯ ಶಿಫಾರಸು ಅಲ್ಲ.";

export async function POST(
  _request: NextRequest,
  context: { params: Promise<{ leadId: string }> },
) {
  if (!isSupabaseConfigured()) {
    return jsonError("Supabase is not configured.", 503);
  }

  const { leadId } = await context.params;
  const supabase = createSupabaseServiceClient();

  // Get latest generated content
  const { data: contentRow, error: contentError } = await supabase
    .from("generated_content")
    .select("id,content_en,content_kn,status,validation_report")
    .eq("lead_id", leadId)
    .order("created_at", { ascending: false })
    .limit(1)
    .single();

  if (contentError || !contentRow) {
    return jsonError("No generated content found.", 404);
  }

  // Deploy gate (P0-4/P0-5): only fully human-approved bilingual content ships.
  const stateGate = evaluateDeployState({
    status: contentRow.status,
    hasEnglish: Boolean(contentRow.content_en),
    hasKannada: Boolean(contentRow.content_kn),
  });
  if (!stateGate.ok) {
    return jsonError(stateGate.reason, stateGate.code);
  }

  // Re-validate everything one final time before it goes external.
  const content = contentRow.content_en as unknown as GeneratedContent;
  const kannada = contentRow.content_kn as unknown as GeneratedContent;
  const { data: verifiedFacts } = await supabase
    .from("hospital_facts")
    .select("id,fact_type,value,source_excerpt")
    .eq("lead_id", leadId)
    .eq("verification_status", "VERIFIED");

  const facts = verifiedFacts ?? [];
  const verifiedIds = facts.map((f) => f.id);
  const validation = validateClaims(content, facts);
  const kannadaValidation = validateKannada(content, kannada, verifiedIds);

  const validationGate = evaluateDeployValidation({
    englishValid: validation.valid,
    kannadaValid: kannadaValidation.valid,
  });
  if (!validationGate.ok) {
    await supabase
      .from("generated_content")
      .update({
        status: "BLOCKED",
        validation_report: {
          english: validation,
          kannada: kannadaValidation,
        } as unknown as Json,
      })
      .eq("id", contentRow.id);

    return jsonError(
      `Validation failed before deploy: ${validation.issues.length} English + ${kannadaValidation.issues.length} Kannada issue(s). Preview blocked.`,
      422,
    );
  }

  // Idempotent: reuse an existing live preview for this content instead of
  // stacking duplicates on repeated deploy clicks.
  const { data: existingPreview } = await supabase
    .from("previews")
    .select("id,slug,status")
    .eq("generated_content_id", contentRow.id)
    .neq("status", "REMOVED")
    .order("created_at", { ascending: false })
    .limit(1)
    .maybeSingle();

  if (existingPreview) {
    return NextResponse.json({
      ok: true,
      preview: existingPreview,
      previewUrl: `/preview/${existingPreview.slug}`,
      validation,
      reused: true,
    });
  }

  // Generate slug and create preview
  const slug = generatePreviewSlug();
  const staleAfter = computeStaleAfter();

  const { data: preview, error: previewError } = await supabase
    .from("previews")
    .insert({
      lead_id: leadId,
      generated_content_id: contentRow.id,
      slug,
      disclaimer_en: disclaimerEn,
      disclaimer_kn: disclaimerKn,
      noindex: true,
      status: "READY",
      deployed_at: new Date().toISOString(),
      stale_after: staleAfter.toISOString(),
    })
    .select()
    .single();

  if (previewError) {
    return jsonError(`Failed to create preview: ${previewError.message}`, 500);
  }

  // Update lead status
  await supabase
    .from("leads")
    .update({ status: "PREVIEW_READY" })
    .eq("id", leadId);

  // Update content status
  await supabase
    .from("generated_content")
    .update({ status: "VALIDATED" })
    .eq("id", contentRow.id);

  return NextResponse.json({
    ok: true,
    preview,
    previewUrl: `/preview/${slug}`,
    validation,
  });
}
