import { NextResponse, type NextRequest } from "next/server";

import type { Json } from "@/lib/database/types";
import { generatePreviewSlug, computeStaleAfter } from "@/lib/preview/slug";
import { validateClaims } from "@/lib/content/claim-validator";
import type { GeneratedContent } from "@/lib/content/content-schema";
import {
  createSupabaseServiceClient,
  isSupabaseConfigured,
} from "@/lib/supabase/server";

export const runtime = "nodejs";

function jsonError(message: string, status = 400) {
  return NextResponse.json({ ok: false, message }, { status });
}

const disclaimerEn =
  "UNOFFICIAL PREVIEW — This page was generated by Nasken AI as a technology preview. It is not affiliated with, endorsed by, or published by the hospital. All information shown was sourced from publicly available data and verified by a human reviewer. This page is not a medical recommendation.";

const disclaimerKn =
  "ಅನಧಿಕೃತ ಪೂರ್ವವೀಕ್ಷಣೆ — ಈ ಪುಟವನ್ನು ನ್ಯಾಸ್ಕನ್ AI ತಂತ್ರಜ್ಞಾನ ಪೂರ್ವವೀಕ್ಷಣೆಯಾಗಿ ರಚಿಸಿದೆ. ಇದು ಆಸ್ಪತ್ರೆಯಿಂದ ಅಧಿಕೃತವಾಗಿ ಪ್ರಕಟಿಸಲ್ಪಟ್ಟಿಲ್ಲ. ತೋರಿಸಲಾದ ಎಲ್ಲಾ ಮಾಹಿತಿಯನ್ನು ಸಾರ್ವಜನಿಕವಾಗಿ ಲಭ್ಯವಿರುವ ಡೇಟಾದಿಂದ ಪಡೆಯಲಾಗಿದೆ. ಇದು ವೈದ್ಯಕೀಯ ಶಿಫಾರಸು ಅಲ್ಲ.";

export async function POST(
  _request: NextRequest,
  context: { params: Promise<{ leadId: string }> },
) {
  if (!isSupabaseConfigured()) {
    return jsonError("Supabase is not configured.", 503);
  }

  const { leadId } = await context.params;
  const supabase = createSupabaseServiceClient();

  // Get latest generated content
  const { data: contentRow, error: contentError } = await supabase
    .from("generated_content")
    .select("id,content_en,content_kn,status,validation_report")
    .eq("lead_id", leadId)
    .order("created_at", { ascending: false })
    .limit(1)
    .single();

  if (contentError || !contentRow) {
    return jsonError("No generated content found.", 404);
  }

  if (contentRow.status === "BLOCKED") {
    return jsonError("Content is blocked due to failed claim validation.", 422);
  }

  // Re-validate claims one more time
  const content = contentRow.content_en as unknown as GeneratedContent;
  const { data: verifiedFacts } = await supabase
    .from("hospital_facts")
    .select("id")
    .eq("lead_id", leadId)
    .eq("verification_status", "VERIFIED");

  const verifiedIds = (verifiedFacts ?? []).map((f) => f.id);
  const validation = validateClaims(content, verifiedIds);

  if (!validation.valid) {
    // Update content to BLOCKED
    await supabase
      .from("generated_content")
      .update({
        status: "BLOCKED",
        validation_report: validation as unknown as Json,
      })
      .eq("id", contentRow.id);

    return jsonError(
      `Claim validation failed: ${validation.issues.length} issues. Preview blocked.`,
      422,
    );
  }

  // Generate slug and create preview
  const slug = generatePreviewSlug();
  const staleAfter = computeStaleAfter();

  const { data: preview, error: previewError } = await supabase
    .from("previews")
    .insert({
      lead_id: leadId,
      generated_content_id: contentRow.id,
      slug,
      disclaimer_en: disclaimerEn,
      disclaimer_kn: disclaimerKn,
      noindex: true,
      status: "READY",
      deployed_at: new Date().toISOString(),
      stale_after: staleAfter.toISOString(),
    })
    .select()
    .single();

  if (previewError) {
    return jsonError(`Failed to create preview: ${previewError.message}`, 500);
  }

  // Update lead status
  await supabase
    .from("leads")
    .update({ status: "PREVIEW_READY" })
    .eq("id", leadId);

  // Update content status
  await supabase
    .from("generated_content")
    .update({ status: "VALIDATED" })
    .eq("id", contentRow.id);

  return NextResponse.json({
    ok: true,
    preview,
    previewUrl: `/preview/${slug}`,
    validation,
  });
}
