import { AlertTriangle } from "lucide-react";
import { notFound } from "next/navigation";
import type { Metadata } from "next";

import { PreviewRenderer } from "@/components/preview/preview-renderer";
import type { GeneratedContent } from "@/lib/content/content-schema";
import type { TemplateKey } from "@/lib/content/content-schema";
import {
  createSupabaseServiceClient,
  isSupabaseConfigured,
} from "@/lib/supabase/server";

export const dynamic = "force-dynamic";

type PreviewPageProps = {
  params: Promise<{ slug: string }>;
  searchParams: Promise<{ lang?: string }>;
};

export async function generateMetadata({
  params,
}: PreviewPageProps): Promise<Metadata> {
  return {
    robots: { index: false, follow: false },
    title: "Hospital Preview — Nasken AI",
  };
}

async function getPreviewData(slug: string) {
  if (!isSupabaseConfigured()) return null;

  const supabase = createSupabaseServiceClient();

  const { data: preview } = await supabase
    .from("previews")
    .select(
      "id,lead_id,generated_content_id,slug,disclaimer_en,disclaimer_kn,status,stale_after",
    )
    .eq("slug", slug)
    .single();

  if (!preview || preview.status === "REMOVED") return null;

  // Check staleness
  if (preview.stale_after && new Date(preview.stale_after) < new Date()) {
    return null;
  }

  // Get content
  const { data: contentRow } = await supabase
    .from("generated_content")
    .select("template_key,content_en,content_kn")
    .eq("id", preview.generated_content_id!)
    .single();

  if (!contentRow) return null;

  // Log analytics event
  await supabase.from("analytics_events").insert({
    lead_id: preview.lead_id,
    preview_id: preview.id,
    event: "preview_opened",
    device_category: "unknown",
  });

  return {
    preview,
    templateKey: contentRow.template_key as TemplateKey,
    contentEn: contentRow.content_en as unknown as GeneratedContent,
    contentKn: contentRow.content_kn as unknown as GeneratedContent | null,
  };
}

export default async function PreviewPage({ params, searchParams }: PreviewPageProps) {
  const { slug } = await params;
  const { lang } = await searchParams;
  const data = await getPreviewData(slug);

  if (!data) {
    notFound();
  }

  const isKannada = lang === "kn" && data.contentKn !== null;
  const content = isKannada ? data.contentKn! : data.contentEn;
  const disclaimer = isKannada
    ? data.preview.disclaimer_kn ?? data.preview.disclaimer_en
    : data.preview.disclaimer_en;

  return (
    <>
      <meta name="robots" content="noindex, nofollow" />
      <div className="min-h-screen bg-white">
        {/* Disclaimer banner */}
        <div className="border-b border-amber-200 bg-amber-50 px-4 py-3">
          <div className="mx-auto flex max-w-5xl items-start gap-3">
            <AlertTriangle
              className="mt-0.5 shrink-0 text-amber-600"
              size={18}
              aria-hidden="true"
            />
            <p className="text-xs leading-5 text-amber-900">{disclaimer}</p>
          </div>
        </div>

        {/* Language toggle */}
        {data.contentKn && (
          <div className="border-b border-slate-100 bg-slate-50 px-4 py-2">
            <div className="mx-auto flex max-w-5xl justify-end gap-2">
              <a
                href={`/preview/${slug}`}
                className={`rounded-md px-3 py-1 text-xs font-medium ${!isKannada ? "bg-teal-700 text-white" : "bg-white text-slate-700 border border-slate-300"}`}
              >
                English
              </a>
              <a
                href={`/preview/${slug}?lang=kn`}
                className={`rounded-md px-3 py-1 text-xs font-medium ${isKannada ? "bg-teal-700 text-white" : "bg-white text-slate-700 border border-slate-300"}`}
              >
                ಕನ್ನಡ
              </a>
            </div>
          </div>
        )}

        {/* Preview content */}
        <PreviewRenderer
          content={content}
          templateKey={data.templateKey}
          slug={slug}
        />

        {/* Footer */}
        <footer className="border-t border-slate-200 bg-slate-50 px-4 py-6">
          <div className="mx-auto max-w-5xl text-center text-xs text-slate-500">
            <p>Preview generated by Nasken AI — not an official hospital website.</p>
          </div>
        </footer>
      </div>
    </>
  );
}
