/**
 * Controlled bilingual UI string table (Section 33). Generic chrome copy only —
 * hospital-specific FACTUAL content is never routed through here; it flows from
 * the normalized model and the established translation/parity safeguards.
 */

export type Lang = "en" | "kn";

const STRINGS = {
  nav_specialties: { en: "Specialties", kn: "ವಿಶೇಷತೆಗಳು" },
  nav_doctors: { en: "Doctors", kn: "ವೈದ್ಯರು" },
  nav_facilities: { en: "Facilities", kn: "ಸೌಲಭ್ಯಗಳು" },
  nav_about: { en: "About", kn: "ನಮ್ಮ ಬಗ್ಗೆ" },
  nav_contact: { en: "Contact", kn: "ಸಂಪರ್ಕ" },

  book_appointment: { en: "Book Appointment", kn: "ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ಕಾಯ್ದಿರಿಸಿ" },
  find_a_doctor: { en: "Find a Doctor", kn: "ವೈದ್ಯರನ್ನು ಹುಡುಕಿ" },
  call_hospital: { en: "Call Hospital", kn: "ಆಸ್ಪತ್ರೆಗೆ ಕರೆ ಮಾಡಿ" },
  get_directions: { en: "Get Directions", kn: "ದಾರಿ ಪಡೆಯಿರಿ" },
  emergency: { en: "Emergency", kn: "ತುರ್ತು" },

  our_specialties: { en: "Our Specialties", kn: "ನಮ್ಮ ವಿಶೇಷತೆಗಳು" },
  facilities_services: { en: "Facilities & Services", kn: "ಸೌಲಭ್ಯಗಳು ಮತ್ತು ಸೇವೆಗಳು" },
  our_doctors: { en: "Our Doctors", kn: "ನಮ್ಮ ವೈದ್ಯರು" },
  about_the_hospital: { en: "About the Hospital", kn: "ಆಸ್ಪತ್ರೆಯ ಬಗ್ಗೆ" },
  for_patients: { en: "For Patients", kn: "ರೋಗಿಗಳಿಗಾಗಿ" },
  our_journey: { en: "Our Journey", kn: "ನಮ್ಮ ಪಯಣ" },
  founder: { en: "Founder", kn: "ಸಂಸ್ಥಾಪಕ" },

  view_all_specialties: { en: "View all specialties", kn: "ಎಲ್ಲಾ ವಿಶೇಷತೆಗಳನ್ನು ನೋಡಿ" },
  view_all_doctors: { en: "View all doctors", kn: "ಎಲ್ಲಾ ವೈದ್ಯರನ್ನು ನೋಡಿ" },
  view_all_facilities: { en: "View all facilities", kn: "ಎಲ್ಲಾ ಸೌಲಭ್ಯಗಳನ್ನು ನೋಡಿ" },

  emergency_services: { en: "Emergency Services", kn: "ತುರ್ತು ಸೇವೆಗಳು" },
  visit_us: { en: "Visit Us", kn: "ನಮ್ಮನ್ನು ಭೇಟಿ ಮಾಡಿ" },
  need_appointment: { en: "Need an appointment?", kn: "ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ಬೇಕೇ?" },
  address_label: { en: "Address", kn: "ವಿಳಾಸ" },
  phone_label: { en: "Phone", kn: "ದೂರವಾಣಿ" },
  email_label: { en: "Email", kn: "ಇಮೇಲ್" },
  learn_more: { en: "Learn more", kn: "ಇನ್ನಷ್ಟು ತಿಳಿಯಿರಿ" },
  specialists: { en: "specialists", kn: "ತಜ್ಞರು" },
  unofficial_preview: {
    en: "Unofficial preview generated by Nasken AI — not the hospital's official website.",
    kn: "Nasken AI ರಚಿಸಿದ ಅನಧಿಕೃತ ಮುನ್ನೋಟ — ಇದು ಆಸ್ಪತ್ರೆಯ ಅಧಿಕೃತ ವೆಬ್‌ಸೈಟ್ ಅಲ್ಲ.",
  },
} as const;

export type StringKey = keyof typeof STRINGS;

export function t(key: StringKey, lang: Lang): string {
  const entry = STRINGS[key];
  return entry ? entry[lang] : String(key);
}
